version: '3'

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks: 
      - eth-api-app
    links:
      - mongo
    command: npm run dev
  mongo:
    container_name: mongo
    image: mongo
    networks: 
      - eth-api-app
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

networks:
  eth-api-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
